var error_msgs = {
	"rent_high": "Families that pay more than 30% of their income towards rent may not have enough money for other living expenses such as food and healthcare.",

	"tax_credit_equity_disabled" : "You've raised rents above an affordable level and no longer quality for tax credit equity.",
	"noi_label": "No lender would make a loan to a property with negative NOI, and you have insufficient funds to operate the property.",
	"average_monthly_rent" : "An error message",
	"average_monthly_rent_invalid" : "This value falls outside the valid range.",
	"vacancy_rate" : "An error message",
	"vacancy_rate_invalid" : "This value falls outside the valid range.",
	"replacement_reserve_rate" : "Lowering this below the modeled number may result in unmet capital needs, an inability to raise debt, and/or eventual property failure.",
	"replacement_reserve_rate_invalid" : "This value falls outside the valid range.",
	"admin_expenses" : "Reducing administrative expenses below the modeled number may not provide enough funds to sufficiently staff the property.",
	"admin_expenses_invalid" : "This value falls outside the valid range.",
	"operating_expenses" : "Reducing operating expenses below the modeled number may not provide enough funds to operate the property.",
	"operating_expenses_invalid" : "This value falls outside the valid range.",
	"maintenance_expenses" : "Reducing maintenance expenses below the modeled number may not provide enough funds to maintain the property.",
	"maintenance_expenses_invalid" : "This value falls outside the valid range.",
	"noi" : "An error message",
	"noi_invalid" : "This value falls outside the valid range.",
	"debt_service_coverage" : "An error message",
	"debt_service_coverage_invalid" : "This value falls outside the valid range.",
	"interest_rate" : "An error message",
	"interest_rate_invalid" : "This value falls outside the valid range.",
	"capitalization_rate" : "An error message",
	"capitalization_rate_invalid" : "This value falls outside the valid range.",
	"loan_to_value" : "An error message",
	"loan_to_value_invalid" : "This value falls outside the valid range.",
	"debt" : "An error message",
	"debt_invalid" : "This value falls outside the valid range.",
	"deferred_developer_fee" : "Deferring too much of the developer fee may cause the development business to fail.",
	"deferred_developer_fee_invalid" : "This value falls outside the valid range.",
	"tax_credit_equity" : "An error message",
	"tax_credit_equity_invalid" : "This value falls outside the valid range.",
	"acquisition_costs" : "Reducing acquisition costs below the modeled number may not provide enough funding to acquire the land for the development.",
	"acquisition_costs_invalid" : "This value falls outside the valid range.",
	"construction_costs" : "Reducing construction costs below the modeled number may not provide enough funding to build the property.",
	"construction_costs_invalid" : "This value falls outside the valid range.",
	"design_fees" : "Reducing design fees below the modeled number may not provide enough funding to design the development.",
	"design_fees_invalid" : "This value falls outside the valid range.",
	"interim_costs" : "Reducing interim costs below the modeled number may not provide enough funding to cover the costs of the construction loan.",
	"interim_costs_invalid" : "This value falls outside the valid range.",
	"permanent_financing_fees" : "An error message",
	"permanent_financing_fees_invalid" : "This value falls outside the valid range.",
	"operating_and_debt_service_reserves" : "You have decreased the reserves below the modeled figure for Denver in 2015. Insufficient operating/debt service reserve could cause the lender to refuse to make the loan and risks failure of the project.",
	"operating_and_debt_service_reserves_invalid" : "This value falls outside the valid range.",
	"developers_fee" : "An error message",
	"developers_fee_invalid" : "This value falls outside the valid range.",
	"project_management" : "An error message",
	"project_management_invalid" : "This value falls outside the valid range."
}