var error_msgs = {
	"tax_credit_50" : "These public dollars are awarded through competition. They are in short supply and may not be cost effective for smaller projects.",
	"tax_credit_high": "These public dollars are awarded through competition and are in short supply. There are limits on the amount of tax credits that can be awarded to one property.",
	"rent_high" : "Families that pay more than 30 percent of their income toward rent may not have enough money for food, health care, and other living expenses.",
	"tax_credit_equity_disabled" : "You’ve raised rent too high to qualify for tax credit equity.",
	"noi_label": "You don’t have enough funds to operate the property. No lender would make a loan to a property with negative NOI.",
	"average_monthly_rent" : "An error message",
	"average_monthly_rent_invalid" : "This value falls outside the valid range.",
	"vacancy_rate" : "An error message",
	"vacancy_rate_invalid" : "This value falls outside the valid range.",
	"replacement_reserve_rate" : "Lowering the replacement reserve rate may result in unmet capital needs, an inability to raise debt, and/or eventual property failure.",
	"replacement_reserve_rate_invalid" : "This value falls outside the valid range.",
	"admin_expenses" : "Reducing administrative expenses may not provide enough money to pay the staff you need to operate the building.",
	"admin_expenses_invalid" : "This value falls outside the valid range.",
	"operating_expenses" : "Reducing operating expenses may not provide enough funds to effectively operate the property.",
	"operating_expenses_invalid" : "This value falls outside the valid range.",
	"maintenance_expenses" : "Reducing maintenance expenses may not provide enough funds to maintain the property over time.",
	"maintenance_expenses_invalid" : "This value falls outside the valid range.",
	"noi" : "An error message",
	"noi_invalid" : "This value falls outside the valid range.",
	"debt_service_coverage" : "An error message",
	"debt_service_coverage_invalid" : "This value falls outside the valid range.",
	"interest_rate" : "An error message",
	"interest_rate_invalid" : "This value falls outside the valid range.",
	"capitalization_rate" : "An error message",
	"capitalization_rate_invalid" : "This value falls outside the valid range.",
	"loan_to_value" : "An error message",
	"loan_to_value_invalid" : "This value falls outside the valid range.",
	"debt" : "An error message",
	"debt_invalid" : "This value falls outside the valid range.",
	"deferred_developer_fee" : "Deferring too much of the developer fee may cause the development business to fail.",
	"deferred_developer_fee_invalid" : "This value falls outside the valid range.",
	"tax_credit_equity" : "An error message",
	"tax_credit_equity_invalid" : "This value falls outside the valid range.",
	"acquisition_costs" : "Reducing acquisition costs below the modeled number may not provide enough funding to acquire the land for the development.",
	"acquisition_costs_invalid" : "This value falls outside the valid range.",
	"construction_costs" : "Buildings must comply with regulations and codes, so make sure you have enough funds to properly build the apartments.",
	"construction_costs_invalid" : "This value falls outside the valid range.",
	"design_fees" : "Reducing design fees below the modeled number may not provide enough funding to design the development.",
	"design_fees_invalid" : "This value falls outside the valid range.",
	"interim_costs" : "If you don’t have enough funding to cover the costs of the construction loan, you may default on that loan before you can complete the building.",
	"interim_costs_invalid" : "This value falls outside the valid range.",
	"permanent_financing_fees" : "An error message",
	"permanent_financing_fees_invalid" : "This value falls outside the valid range.",
	"operating_and_debt_service_reserves" : "If you don’t have enough reserves, your lender may refuse to make the loan and your project may fail.",
	"operating_and_debt_service_reserves_invalid" : "This value falls outside the valid range.",
	"developers_fee" : "An error message",
	"developers_fee_invalid" : "This value falls outside the valid range.",
	"project_management" : "An error message",
	"project_management_invalid" : "This value falls outside the valid range."
}