var help_msgs = {
	"help_equity": "Investment in the real estate represented by an ownership interest. Return to equity is paid after return to debt, in most instances.",
	"help_average_monthly_rent" : "Rent varies by apartment size. We use an average, weighted by the number of each apartment size, based on Denver rents. You can change the rent by targeting a different population (increasing or decreasing renter’s income) or by varying the amount you expect a renter to spend on rent.",
	"help_vacancy_rate" : "This rate is used to calculate a property’s lost revenue from units that are vacant or not rentable because of repairs or renovations.",
	"help_replacement_reserve_rate" : "Payments made in escrow to cover the costs of capital needs and major systems repairs and replacements that occur as the property ages: for example, replacing appliances, air conditioners, water heaters, and roofs.",
	"help_admin_expenses" : "Includes staff salaries, health insurance and other benefits, advertising and office supplies.",
	"help_operating_expenses" : "Owner-paid utilities, fire and liability insurance, and trash removal.",
	"help_maintenance_expenses" : "Property maintenance and repair costs, separate from major capital improvements.",
	"help_noi" : "Rental income remaining after payment of ongoing property expenses and vacancy losses. The net operating income is based on the monthly rent expected for each apartment size (1, 2, or 3 bedroom) multiplied by the total number of units multiplied by 12 to get the annual income.",
	"help_debt_service_coverage" : "A calculation to ensure the property has enough income to cover its debt obligation based on the relationship between the net operating income (NOI) of a project to the amount of debt service the NOI must be used to pay.",
	"help_interest_rate" : "The interest rate applicable to the borrowed funds. We set the default interest rate to 5 percent based on current rates for multifamily commercial loans.",
	"help_capitalization_rate" : "Measures the estimated rate of return of the capital invested in a property at the time of purchase or initial stabilized year. Dividing projected annual income by the capitalization rate produces a present-day asset value.",
	"help_loan_to_value" : "The loan amount divided by the property’s value based on the capitalization rate and NOI.",
	"help_debt" : "The amount of money borrowed from a financial institution to permanently finance a multifamily housing property. The borrower must repay the loan, plus interest, by a certain date, typically 30 years in the future.",
	"help_deferred_developer_fee" : "The portion of the agreed-upon developer fee that the developer is not paid as a development expense, which instead remains as a loan in the rental project. The deferred developer fee may be recovered from the developer’s share of operating cash flow. Once the project is complete, the developer will receive a fraction of the cash flow over time, so after the property pays its obligations, from the remaining funds, a portion goes to the developer.",
	"help_tax_credit_equity" : "The Low Income Housing Tax Credit, a federal program to subsidize creation and preservation of affordable rental housing. Each state receives an annual allocation, which it awards through competition.",
	"help_acquisition_costs" : "Cost to purchase the land and any existing buildings on that land.",
	"help_construction_costs" : "Costs to build the property, including building permit fees, materials, labor, site preparation, infrastructure and landscaping.",
	"help_design_fees" : "Includes interior design, architect, and engineering fees.",
	"help_interim_costs" : "Costs that occur during construction related to interest and fees on the construction loan, insurance during construction, and other holding costs.",
	"help_permanent_financing_fees" : "Fees and expenses related to the mortgage loan, the Low Income Housing Tax Credit, when applicable, and other sources.",
	"help_operating_and_debt_service_reserves" : "Funds set aside regularly for future risks or expenses. For example, the replacement reserve covers replacement of major capital items that occur infrequently. The operating reserve would cover the property’s operating expenses if necessary because of a lower-than-estimated operating income one month.",
	"help_developers_fee" : "Cost of developer’s time and labor to complete the project, including profit for the risk taken and resources used.",
	"help_project_management" : "Fees to cover the costs of administering and managing the development process to completion.",
}