var help_msgs = {
	"help_average_monthly_rent" : "Rent varies by apartment size.  This value is an average of each rent for different units, weighted by the number of each unit type.  Rents in the model are based on market rents for Denver or affordable rents based on 30% or 60 % AMI, depending on options selected.",
	"help_vacancy_rate" : "This term defines the loss to a property from units that are vacant from a tenant ending a lease or not rentable because of repairs or renovations.",
	"help_replacement_reserve_rate" : "Payments made in escrow to cover the costs of capital needs and major systems repairs and replacements that occur as the property ages. For example, replacing appliances, air conditioners, water heaters, and roofs.",
	"help_admin_expenses" : "Staff salaries, health insurance and other benefits, advertising and office supplies.",
	"help_operating_expenses" : "Owner paid utilities, fire and liability insurance and trash removal.",
	"help_maintenance_expenses" : "Property maintenance and repair costs, separate from major capital improvements.",
	"help_noi" : "Rental income remaining after payment of operating costs and vacancy losses. The net operating income is based on the monthly rent expected for each apartment size (1, 2 or 3 bedroom) multiplied by the total number of units multiplied by 12 for the 12 months of the year the property receives rental income.",
	"help_debt_service_coverage" : "A calculation to ensure the property has enough income to cover its debt obligation based on the relationship between the Net Operating Income (NOI) of a project to the amount of debt service the NOI must be used to pay.",
	"help_interest_rate" : "Mortgage interest rate.",
	"help_capitalization_rate" : "Measures the rate of return on total capital invested (i.e., the estimated rate of return on a property at the time of purchase or initial stabilized year). Dividing projected annual income by the capitalization rate produces a present day asset value.",
	"help_loan_to_value" : "The loan amount divided by the property’s value based on the capitalization rate and NOI.",
	"help_debt" : "Borrowing funds from a financial institution to finance a multifamily housing development. The borrower must repay the loan by a certain date, typically 30 years in the future. The borrower must also pay interest on the loan to compensate the lender. Mortgage debt typically amortizes over time, so that the regular payments include both interest and principal.",
	"help_deferred_developer_fee" : "The portion of the agreed-upon developer fee that the developer is not paid as a development expense, which instead remains as a loan in the rental project. The deferred developer fee may be recovered from the developer’s share of operating cash flow.  Once the project is complete, the developer will receive a fraction of the cash flow over time, so after the property pays its obligations, from the remaining funds, a portion would go to the developer.",
	"help_tax_credit_equity" : "Low Income Housing Tax Credit, a federal program to subsidize creation and preservation of affordable rental housing.",
	"help_acquisition_costs" : "Cost to purchase the land and any existing buildings on that land.",
	"help_construction_costs" : "Costs to build the property, including building permit fees, materials, labor, site preparation, infrastructure and landscaping.",
	"help_design_fees" : "Interior design, architect and engineering fees.",
	"help_interim_costs" : "These are costs that occur during construction related to interest and fees on the construction loan, insurance during construction and other holding costs.",
	"help_permanent_financing_fees" : "Fees and expenses related to the mortgage loan and when applicable, fees related to the Low Income Housing Tax Credit.",
	"help_operating_and_debt_service_reserves" : "Funds set aside on a regular schedule for future risks or expenses.  For example, the replacement reserve covers replacement of major capital items that occur infrequently.  The operating reserve would cover the property’s operating expenses if necessary because of a lower than estimated operating income one month.",
	"help_developers_fee" : "Cost to pay the developer for staff time and labor to complete the project, including profit for the risk taken and resources expended.",
	"help_project_management" : "Fees to cover the costs associated with administering and managing the development process to completion.",
}