var help_msgs = {
	"help_average_monthly_rent" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_vacancy_rate" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_replacement_reserve_rate" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_admin_expenses" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_operating_expenses" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_maintenance_expenses" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_noi" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_debt_service_coverage" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_interest_rate" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_capitalization_rate" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_loan_to_value" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_debt" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_deferred_developer_fee" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_tax_credit_equity" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_acquisition_costs" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_construction_costs" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_design_fees" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_interim_costs" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_permanent_financing_fees" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_operating_and_debt_service_reserves" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_developers_fee" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
	"help_project_management" : "This is where some descriptive language goes which will describe what this term is. It will most likely be pulled from the technical report.",
}